# Netlify build configuration for a Vite project

[build]
  command = "npm run build"  # The command to build your site
  publish = "dist"           # The directory containing the built site files

[build.environment]
  NODE_VERSION = "18"        # Specify a Node.js version (optional, but recommended)

# Proxy rule for Google Places API - MUST come before the SPA catch-all rule
[[redirects]]
  from = "/maps-api/*"
  to = "/.netlify/functions/places-proxy/:splat"
  status = 200
  force = true # Ensure this rule takes precedence

# SPA fallback rule
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
